[build]
  command = "pnpm install && pnpm run build"
  publish = "pnpm add -D sass
build" 

[build.environment]
  PNPM_VERSION = "8.15.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200