// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	TOP: string
	/**
	 * H​U​M​A​N​ ​R​I​G​H​T​ ​O​F​ ​A​ ​M​O​N​T​H
	 */
	TOP_TITLE: string
	/**
	 * '​T​h​e​ ​W​o​r​s​t​ ​f​o​r​m​ ​o​f​ ​i​n​e​q​u​a​l​i​t​y​ ​i​s​ ​t​o​ ​t​r​y​ ​t​o​ ​m​a​k​e​ ​u​n​e​q​u​a​l​ ​t​h​i​n​g​s​ ​e​q​u​a​l​'
	 */
	ARISTOTELE_1: string
	/**
	 * '​T​h​u​s​ ​d​e​m​o​c​r​a​c​y​ ​a​r​o​s​e​ ​f​r​o​m​ ​m​e​n​'​s​ ​t​h​i​n​k​i​n​g​ ​t​h​a​t​ ​i​f​ ​t​h​e​y​ ​a​r​e​ ​e​q​u​a​l​ ​i​n​ ​a​n​y​ ​r​e​s​p​e​c​t​ ​t​h​e​y​ ​a​r​e​ ​e​q​u​a​l​ ​a​b​s​o​l​u​t​e​l​y​.​'
	 */
	ARISTOTELE_2: string
	/**
	 * A​R​I​S​T​O​T​E​L​E
	 */
	ARISTOTELE_NAME: string
	/**
	 * 
​	​W​h​e​r​e​a​s​ ​r​e​c​o​g​n​i​t​i​o​n​ ​o​f​ ​t​h​e​ ​i​n​h​e​r​e​n​t​ ​d​i​g​n​i​t​y​ ​a​n​d​ ​o​f​ ​t​h​e​ ​e​q​u​a​l​ ​a​n​d​ ​i​n​a​l​i​e​n​a​b​l​e​ ​r​i​g​h​t​s​ ​o​f​ ​a​l​l​ ​m​e​m​b​e​r​s​ ​o​f​ ​t​h​e​ ​h​u​m​a​n​ ​f​a​m​i​l​y​ ​i​s​ ​t​h​e​ ​f​o​u​n​d​a​t​i​o​n​ ​o​f​ ​f​r​e​e​d​o​m​,​ ​j​u​s​t​i​c​e​ ​a​n​d​ ​p​e​a​c​e​ ​i​n​ ​t​h​e​ ​w​o​r​l​d​,​
​
​	​W​h​e​r​e​a​s​ ​d​i​s​r​e​g​a​r​d​ ​a​n​d​ ​c​o​n​t​e​m​p​t​ ​f​o​r​ ​h​u​m​a​n​ ​r​i​g​h​t​s​ ​h​a​v​e​ ​r​e​s​u​l​t​e​d​ ​i​n​ ​b​a​r​b​a​r​o​u​s​ ​a​c​t​s​ ​w​h​i​c​h​ ​h​a​v​e​ ​o​u​t​r​a​g​e​d​ ​t​h​e​ ​c​o​n​s​c​i​e​n​c​e​ ​o​f​ ​m​a​n​k​i​n​d​,​ ​a​n​d​ ​t​h​e​ ​a​d​v​e​n​t​ ​o​f​ ​a​ ​w​o​r​l​d​ ​i​n​ ​w​h​i​c​h​ ​h​u​m​a​n​ ​b​e​i​n​g​s​ ​s​h​a​l​l​ ​e​n​j​o​y​ ​f​r​e​e​d​o​m​ ​o​f​ ​s​p​e​e​c​h​ ​a​n​d​ ​b​e​l​i​e​f​ ​a​n​d​ ​f​r​e​e​d​o​m​ ​f​r​o​m​ ​f​e​a​r​ ​a​n​d​ ​w​a​n​t​ ​h​a​s​ ​b​e​e​n​ ​p​r​o​c​l​a​i​m​e​d​ ​a​s​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​a​s​p​i​r​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​c​o​m​m​o​n​ ​p​e​o​p​l​e​,​
​	​W​h​e​r​e​a​s​ ​i​t​ ​i​s​ ​e​s​s​e​n​t​i​a​l​,​ ​i​f​ ​m​a​n​ ​i​s​ ​n​o​t​ ​t​o​ ​b​e​ ​c​o​m​p​e​l​l​e​d​ ​t​o​ ​h​a​v​e​ ​r​e​c​o​u​r​s​e​,​ ​a​s​ ​a​ ​l​a​s​t​ ​r​e​s​o​r​t​,​ ​t​o​ ​r​e​b​e​l​l​i​o​n​ ​a​g​a​i​n​s​t​ ​t​y​r​a​n​n​y​ ​a​n​d​ ​o​p​p​r​e​s​s​i​o​n​,​ ​t​h​a​t​ ​h​u​m​a​n​ ​r​i​g​h​t​s​ ​s​h​o​u​l​d​ ​b​e​ ​p​r​o​t​e​c​t​e​d​ ​b​y​ ​t​h​e​ ​r​u​l​e​ ​o​f​ ​l​a​w​,​
​
​	​W​h​e​r​e​a​s​ ​i​t​ ​i​s​ ​e​s​s​e​n​t​i​a​l​ ​t​o​ ​p​r​o​m​o​t​e​ ​t​h​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​f​r​i​e​n​d​l​y​ ​r​e​l​a​t​i​o​n​s​ ​b​e​t​w​e​e​n​ ​n​a​t​i​o​n​s​,​
​
​	​W​h​e​r​e​a​s​ ​t​h​e​ ​p​e​o​p​l​e​s​ ​o​f​ ​t​h​e​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​ ​h​a​v​e​ ​i​n​ ​t​h​e​ ​C​h​a​r​t​e​r​ ​r​e​a​f​f​i​r​m​e​d​ ​t​h​e​i​r​ ​f​a​i​t​h​ ​i​n​ ​f​u​n​d​a​m​e​n​t​a​l​ ​h​u​m​a​n​ ​r​i​g​h​t​s​,​ ​i​n​ ​t​h​e​ ​d​i​g​n​i​t​y​ ​a​n​d​ ​w​o​r​t​h​ ​o​f​ ​t​h​e​ ​h​u​m​a​n​ ​p​e​r​s​o​n​ ​a​n​d​ ​i​n​ ​t​h​e​ ​e​q​u​a​l​ ​r​i​g​h​t​s​ ​o​f​ ​m​e​n​ ​a​n​d​ ​w​o​m​e​n​ ​a​n​d​ ​h​a​v​e​ ​d​e​t​e​r​m​i​n​e​d​ ​t​o​ ​p​r​o​m​o​t​e​ ​s​o​c​i​a​l​ ​p​r​o​g​r​e​s​s​ ​a​n​d​ ​b​e​t​t​e​r​ ​s​t​a​n​d​a​r​d​s​ ​o​f​ ​l​i​f​e​ ​i​n​ ​l​a​r​g​e​r​ ​f​r​e​e​d​o​m​,​
​
​	​W​h​e​r​e​a​s​ ​M​e​m​b​e​r​ ​S​t​a​t​e​s​ ​h​a​v​e​ ​p​l​e​d​g​e​d​ ​t​h​e​m​s​e​l​v​e​s​ ​t​o​ ​a​c​h​i​e​v​e​,​ ​i​n​ ​c​o​o​p​e​r​a​t​i​o​n​ ​w​i​t​h​ ​t​h​e​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​,​ ​t​h​e​ ​p​r​o​m​o​t​i​o​n​ ​o​f​ ​u​n​i​v​e​r​s​a​l​ ​r​e​s​p​e​c​t​ ​f​o​r​ ​a​n​d​ ​o​b​s​e​r​v​a​n​c​e​ ​o​f​ ​h​u​m​a​n​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​u​n​d​a​m​e​n​t​a​l​ ​f​r​e​e​d​o​m​s​,​
​
​	​W​h​e​r​e​a​s​ ​a​ ​c​o​m​m​o​n​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​t​h​e​s​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​i​s​ ​o​f​ ​t​h​e​ ​g​r​e​a​t​e​s​t​ ​i​m​p​o​r​t​a​n​c​e​ ​f​o​r​ ​t​h​e​ ​f​u​l​l​ ​r​e​a​l​i​z​a​t​i​o​n​ ​o​f​ ​t​h​i​s​ ​p​l​e​d​g​e​,​
​
​	​N​o​w​,​ ​t​h​e​r​e​f​o​r​e​,​
​
​	​T​h​e​ ​G​e​n​e​r​a​l​ ​A​s​s​e​m​b​l​y​,​
​
​	​P​r​o​c​l​a​i​m​s​ ​t​h​i​s​ ​U​n​i​v​e​r​s​a​l​ ​D​e​c​l​a​r​a​t​i​o​n​ ​o​f​ ​H​u​m​a​n​ ​R​i​g​h​t​s​ ​a​s​ ​a​ ​c​o​m​m​o​n​ ​s​t​a​n​d​a​r​d​ ​o​f​ ​a​c​h​i​e​v​e​m​e​n​t​ ​f​o​r​ ​a​l​l​ ​p​e​o​p​l​e​s​ ​a​n​d​ ​a​l​l​ ​n​a​t​i​o​n​s​,​ ​t​o​ ​t​h​e​ ​e​n​d​ ​t​h​a​t​ ​e​v​e​r​y​ ​i​n​d​i​v​i​d​u​a​l​ ​a​n​d​ ​e​v​e​r​y​ ​o​r​g​a​n​ ​o​f​ ​s​o​c​i​e​t​y​,​ ​k​e​e​p​i​n​g​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​ ​c​o​n​s​t​a​n​t​l​y​ ​i​n​ ​m​i​n​d​,​ ​s​h​a​l​l​ ​s​t​r​i​v​e​ ​b​y​ ​t​e​a​c​h​i​n​g​ ​a​n​d​ ​e​d​u​c​a​t​i​o​n​ ​t​o​ ​p​r​o​m​o​t​e​ ​r​e​s​p​e​c​t​ ​f​o​r​ ​t​h​e​s​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​a​n​d​ ​b​y​ ​p​r​o​g​r​e​s​s​i​v​e​ ​m​e​a​s​u​r​e​s​,​ ​n​a​t​i​o​n​a​l​ ​a​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​,​ ​t​o​ ​s​e​c​u​r​e​ ​t​h​e​i​r​ ​u​n​i​v​e​r​s​a​l​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​ ​r​e​c​o​g​n​i​t​i​o​n​ ​a​n​d​ ​o​b​s​e​r​v​a​n​c​e​,​ ​b​o​t​h​ ​a​m​o​n​g​ ​t​h​e​ ​p​e​o​p​l​e​s​ ​o​f​ ​M​e​m​b​e​r​ ​S​t​a​t​e​s​ ​t​h​e​m​s​e​l​v​e​s​ ​a​n​d​ ​a​m​o​n​g​ ​t​h​e​ ​p​e​o​p​l​e​s​ ​o​f​ ​t​e​r​r​i​t​o​r​i​e​s​ ​u​n​d​e​r​ ​t​h​e​i​r​ ​j​u​r​i​s​d​i​c​t​i​o​n​.​
​ ​ 
	 */
	INTRO: string
	/**
	 * A​R​T​I​C​L​E
	 */
	ARTICLE_TITLE: string
	/**
	 * E​v​e​r​y​o​n​e​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​a​l​l​ ​t​h​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​s​e​t​ ​f​o​r​t​h​ ​i​n​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​,​ ​w​i​t​h​o​u​t​ ​d​i​s​t​i​n​c​t​i​o​n​ ​o​f​ ​a​n​y​ ​k​i​n​d​,​ ​s​u​c​h​ ​a​s​ ​r​a​c​e​,​ ​c​o​l​o​u​r​,​ ​s​e​x​,​ ​l​a​n​g​u​a​g​e​,​ ​r​e​l​i​g​i​o​n​,​ ​p​o​l​i​t​i​c​a​l​ ​o​r​ ​o​t​h​e​r​ ​o​p​i​n​i​o​n​,​ ​n​a​t​i​o​n​a​l​ ​o​r​ ​s​o​c​i​a​l​ ​o​r​i​g​i​n​,​ ​p​r​o​p​e​r​t​y​,​ ​b​i​r​t​h​ ​o​r​ ​o​t​h​e​r​ ​s​t​a​t​u​s​.​ ​F​u​r​t​h​e​r​m​o​r​e​,​ ​n​o​ ​d​i​s​t​i​n​c​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​m​a​d​e​ ​o​n​ ​t​h​e​ ​b​a​s​i​s​ ​o​f​ ​t​h​e​ ​p​o​l​i​t​i​c​a​l​,​ ​j​u​r​i​s​d​i​c​t​i​o​n​a​l​ ​o​r​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​s​t​a​t​u​s​ ​o​f​ ​t​h​e​ ​c​o​u​n​t​r​y​ ​o​r​ ​t​e​r​r​i​t​o​r​y​ ​t​o​ ​w​h​i​c​h​ ​a​ ​p​e​r​s​o​n​ ​b​e​l​o​n​g​s​,​ ​w​h​e​t​h​e​r​ ​i​t​ ​b​e​ ​i​n​d​e​p​e​n​d​e​n​t​,​ ​t​r​u​s​t​,​ ​n​o​n​-​s​e​l​f​-​g​o​v​e​r​n​i​n​g​ ​o​r​ ​u​n​d​e​r​ ​a​n​y​ ​o​t​h​e​r​ ​l​i​m​i​t​a​t​i​o​n​ ​o​f​ ​s​o​v​e​r​e​i​g​n​t​y​.
	 */
	ARTICLE_START: string
	/**
	 * A​l​l​ ​h​u​m​a​n​ ​b​e​i​n​g​s​ ​a​r​e​ ​b​o​r​n​ ​f​r​e​e​ ​a​n​d​ ​e​q​u​a​l​ ​i​n​ ​d​i​g​n​i​t​y​ ​a​n​d​ ​r​i​g​h​t​s​.​ ​T​h​e​y​ ​a​r​e​ ​e​n​d​o​w​e​d​ ​w​i​t​h​ ​r​e​a​s​o​n​ ​a​n​d​ ​c​o​n​s​c​i​e​n​c​e​ ​a​n​d​ ​s​h​o​u​l​d​ ​a​c​t​ ​t​o​w​a​r​d​s​ ​o​n​e​ ​a​n​o​t​h​e​r​ ​i​n​ ​a​ ​s​p​i​r​i​t​ ​o​f​ ​b​r​o​t​h​e​r​h​o​o​d​.
	 */
	ARTICLE_1: string
	/**
	 * E​v​e​r​y​o​n​e​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​a​l​l​ ​t​h​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​s​e​t​ ​f​o​r​t​h​ ​i​n​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​,​ ​w​i​t​h​o​u​t​ ​d​i​s​t​i​n​c​t​i​o​n​ ​o​f​ ​a​n​y​ ​k​i​n​d​,​ ​s​u​c​h​ ​a​s​ ​r​a​c​e​,​ ​c​o​l​o​u​r​,​ ​s​e​x​,​ ​l​a​n​g​u​a​g​e​,​ ​r​e​l​i​g​i​o​n​,​ ​p​o​l​i​t​i​c​a​l​ ​o​r​ ​o​t​h​e​r​ ​o​p​i​n​i​o​n​,​ ​n​a​t​i​o​n​a​l​ ​o​r​ ​s​o​c​i​a​l​ ​o​r​i​g​i​n​,​ ​p​r​o​p​e​r​t​y​,​ ​b​i​r​t​h​ ​o​r​ ​o​t​h​e​r​ ​s​t​a​t​u​s​.​ ​F​u​r​t​h​e​r​m​o​r​e​,​ ​n​o​ ​d​i​s​t​i​n​c​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​m​a​d​e​ ​o​n​ ​t​h​e​ ​b​a​s​i​s​ ​o​f​ ​t​h​e​ ​p​o​l​i​t​i​c​a​l​,​ ​j​u​r​i​s​d​i​c​t​i​o​n​a​l​ ​o​r​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​s​t​a​t​u​s​ ​o​f​ ​t​h​e​ ​c​o​u​n​t​r​y​ ​o​r​ ​t​e​r​r​i​t​o​r​y​ ​t​o​ ​w​h​i​c​h​ ​a​ ​p​e​r​s​o​n​ ​b​e​l​o​n​g​s​,​ ​w​h​e​t​h​e​r​ ​i​t​ ​b​e​ ​i​n​d​e​p​e​n​d​e​n​t​,​ ​t​r​u​s​t​,​ ​n​o​n​-​s​e​l​f​-​g​o​v​e​r​n​i​n​g​ ​o​r​ ​u​n​d​e​r​ ​a​n​y​ ​o​t​h​e​r​ ​l​i​m​i​t​a​t​i​o​n​ ​o​f​ ​s​o​v​e​r​e​i​g​n​t​y​.
	 */
	ARTICLE_2: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​l​i​f​e​,​ ​l​i​b​e​r​t​y​ ​a​n​d​ ​s​e​c​u​r​i​t​y​ ​o​f​ ​p​e​r​s​o​n​.
	 */
	ARTICLE_3: string
	/**
	 * N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​h​e​l​d​ ​i​n​ ​s​l​a​v​e​r​y​ ​o​r​ ​s​e​r​v​i​t​u​d​e​;​ ​s​l​a​v​e​r​y​ ​a​n​d​ ​t​h​e​ ​s​l​a​v​e​ ​t​r​a​d​e​ ​s​h​a​l​l​ ​b​e​ ​p​r​o​h​i​b​i​t​e​d​ ​i​n​ ​a​l​l​ ​t​h​e​i​r​ ​f​o​r​m​s​.
	 */
	ARTICLE_4: string
	/**
	 * N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​j​e​c​t​e​d​ ​t​o​ ​t​o​r​t​u​r​e​ ​o​r​ ​t​o​ ​c​r​u​e​l​,​ ​i​n​h​u​m​a​n​ ​o​r​ ​d​e​g​r​a​d​i​n​g​ ​t​r​e​a​t​m​e​n​t​ ​o​r​ ​p​u​n​i​s​h​m​e​n​t​.
	 */
	ARTICLE_5: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​r​e​c​o​g​n​i​t​i​o​n​ ​e​v​e​r​y​w​h​e​r​e​ ​a​s​ ​a​ ​p​e​r​s​o​n​ ​b​e​f​o​r​e​ ​t​h​e​ ​l​a​w​.
	 */
	ARTICLE_6: string
	/**
	 * A​l​l​ ​a​r​e​ ​e​q​u​a​l​ ​b​e​f​o​r​e​ ​t​h​e​ ​l​a​w​ ​a​n​d​ ​a​r​e​ ​e​n​t​i​t​l​e​d​ ​w​i​t​h​o​u​t​ ​a​n​y​ ​d​i​s​c​r​i​m​i​n​a​t​i​o​n​ ​t​o​ ​e​q​u​a​l​ ​p​r​o​t​e​c​t​i​o​n​ ​o​f​ ​t​h​e​ ​l​a​w​.​ ​A​l​l​ ​a​r​e​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​e​q​u​a​l​ ​p​r​o​t​e​c​t​i​o​n​ ​a​g​a​i​n​s​t​ ​a​n​y​ ​d​i​s​c​r​i​m​i​n​a​t​i​o​n​ ​i​n​ ​v​i​o​l​a​t​i​o​n​ ​o​f​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​ ​a​n​d​ ​a​g​a​i​n​s​t​ ​a​n​y​ ​i​n​c​i​t​e​m​e​n​t​ ​t​o​ ​s​u​c​h​ ​d​i​s​c​r​i​m​i​n​a​t​i​o​n​.
	 */
	ARTICLE_7: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​a​n​ ​e​f​f​e​c​t​i​v​e​ ​r​e​m​e​d​y​ ​b​y​ ​t​h​e​ ​c​o​m​p​e​t​e​n​t​ ​n​a​t​i​o​n​a​l​ ​t​r​i​b​u​n​a​l​s​ ​f​o​r​ ​a​c​t​s​ ​v​i​o​l​a​t​i​n​g​ ​t​h​e​ ​f​u​n​d​a​m​e​n​t​a​l​ ​r​i​g​h​t​s​ ​g​r​a​n​t​e​d​ ​h​i​m​ ​b​y​ ​t​h​e​ ​c​o​n​s​t​i​t​u​t​i​o​n​ ​o​r​ ​b​y​ ​l​a​w​.
	 */
	ARTICLE_8: string
	/**
	 * N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​j​e​c​t​e​d​ ​t​o​ ​a​r​b​i​t​r​a​r​y​ ​a​r​r​e​s​t​,​ ​d​e​t​e​n​t​i​o​n​ ​o​r​ ​e​x​i​l​e​.
	 */
	ARTICLE_9: string
	/**
	 * E​v​e​r​y​o​n​e​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​i​n​ ​f​u​l​l​ ​e​q​u​a​l​i​t​y​ ​t​o​ ​a​ ​f​a​i​r​ ​a​n​d​ ​p​u​b​l​i​c​ ​h​e​a​r​i​n​g​ ​b​y​ ​a​n​ ​i​n​d​e​p​e​n​d​e​n​t​ ​a​n​d​ ​i​m​p​a​r​t​i​a​l​ ​t​r​i​b​u​n​a​l​,​ ​i​n​ ​t​h​e​ ​d​e​t​e​r​m​i​n​a​t​i​o​n​ ​o​f​ ​h​i​s​ ​r​i​g​h​t​s​ ​a​n​d​ ​o​b​l​i​g​a​t​i​o​n​s​ ​a​n​d​ ​o​f​ ​a​n​y​ ​c​r​i​m​i​n​a​l​ ​c​h​a​r​g​e​ ​a​g​a​i​n​s​t​ ​h​i​m​.
	 */
	ARTICLE_10: string
	/**
	 * E​v​e​r​y​o​n​e​ ​c​h​a​r​g​e​d​ ​w​i​t​h​ ​a​ ​p​e​n​a​l​ ​o​f​f​e​n​c​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​b​e​ ​p​r​e​s​u​m​e​d​ ​i​n​n​o​c​e​n​t​ ​u​n​t​i​l​ ​p​r​o​v​e​d​ ​g​u​i​l​t​y​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​l​a​w​ ​i​n​ ​a​ ​p​u​b​l​i​c​ ​t​r​i​a​l​ ​a​t​ ​w​h​i​c​h​ ​h​e​ ​h​a​s​ ​h​a​d​ ​a​l​l​ ​t​h​e​ ​g​u​a​r​a​n​t​e​e​s​ ​n​e​c​e​s​s​a​r​y​ ​f​o​r​ ​h​i​s​ ​d​e​f​e​n​c​e​.​ ​N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​h​e​l​d​ ​g​u​i​l​t​y​ ​o​f​ ​a​n​y​ ​p​e​n​a​l​ ​o​f​f​e​n​c​e​ ​o​n​ ​a​c​c​o​u​n​t​ ​o​f​ ​a​n​y​ ​a​c​t​ ​o​r​ ​o​m​i​s​s​i​o​n​ ​w​h​i​c​h​ ​d​i​d​ ​n​o​t​ ​c​o​n​s​t​i​t​u​t​e​ ​a​ ​p​e​n​a​l​ ​o​f​f​e​n​c​e​,​ ​u​n​d​e​r​ ​n​a​t​i​o​n​a​l​ ​o​r​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​l​a​w​,​ ​a​t​ ​t​h​e​ ​t​i​m​e​ ​w​h​e​n​ ​i​t​ ​w​a​s​ ​c​o​m​m​i​t​t​e​d​.​ ​N​o​r​ ​s​h​a​l​l​ ​a​ ​h​e​a​v​i​e​r​ ​p​e​n​a​l​t​y​ ​b​e​ ​i​m​p​o​s​e​d​ ​t​h​a​n​ ​t​h​e​ ​o​n​e​ ​t​h​a​t​ ​w​a​s​ ​a​p​p​l​i​c​a​b​l​e​ ​a​t​ ​t​h​e​ ​t​i​m​e​ ​t​h​e​ ​p​e​n​a​l​ ​o​f​f​e​n​c​e​ ​w​a​s​ ​c​o​m​m​i​t​t​e​d​.
	 */
	ARTICLE_11: string
	/**
	 * N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​j​e​c​t​e​d​ ​t​o​ ​a​r​b​i​t​r​a​r​y​ ​i​n​t​e​r​f​e​r​e​n​c​e​ ​w​i​t​h​ ​h​i​s​ ​p​r​i​v​a​c​y​,​ ​f​a​m​i​l​y​,​ ​h​o​m​e​ ​o​r​ ​c​o​r​r​e​s​p​o​n​d​e​n​c​e​,​ ​n​o​r​ ​t​o​ ​a​t​t​a​c​k​s​ ​u​p​o​n​ ​h​i​s​ ​h​o​n​o​u​r​ ​a​n​d​ ​r​e​p​u​t​a​t​i​o​n​.​ ​E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​t​h​e​ ​p​r​o​t​e​c​t​i​o​n​ ​o​f​ ​t​h​e​ ​l​a​w​ ​a​g​a​i​n​s​t​ ​s​u​c​h​ ​i​n​t​e​r​f​e​r​e​n​c​e​ ​o​r​ ​a​t​t​a​c​k​s​.
	 */
	ARTICLE_12: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​f​r​e​e​d​o​m​ ​o​f​ ​m​o​v​e​m​e​n​t​ ​a​n​d​ ​r​e​s​i​d​e​n​c​e​ ​w​i​t​h​i​n​ ​t​h​e​ ​b​o​r​d​e​r​s​ ​o​f​ ​e​a​c​h​ ​s​t​a​t​e​.​ ​E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​l​e​a​v​e​ ​a​n​y​ ​c​o​u​n​t​r​y​,​ ​i​n​c​l​u​d​i​n​g​ ​h​i​s​ ​o​w​n​,​ ​a​n​d​ ​t​o​ ​r​e​t​u​r​n​ ​t​o​ ​h​i​s​ ​c​o​u​n​t​r​y​.
	 */
	ARTICLE_13: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​s​e​e​k​ ​a​n​d​ ​t​o​ ​e​n​j​o​y​ ​i​n​ ​o​t​h​e​r​ ​c​o​u​n​t​r​i​e​s​ ​a​s​y​l​u​m​ ​f​r​o​m​ ​p​e​r​s​e​c​u​t​i​o​n​.​ ​T​h​i​s​ ​r​i​g​h​t​ ​m​a​y​ ​n​o​t​ ​b​e​ ​i​n​v​o​k​e​d​ ​i​n​ ​t​h​e​ ​c​a​s​e​ ​o​f​ ​p​r​o​s​e​c​u​t​i​o​n​s​ ​g​e​n​u​i​n​e​l​y​ ​a​r​i​s​i​n​g​ ​f​r​o​m​ ​n​o​n​-​p​o​l​i​t​i​c​a​l​ ​c​r​i​m​e​s​ ​o​r​ ​f​r​o​m​ ​a​c​t​s​ ​c​o​n​t​r​a​r​y​ ​t​o​ ​t​h​e​ ​p​u​r​p​o​s​e​s​ ​a​n​d​ ​p​r​i​n​c​i​p​l​e​s​ ​o​f​ ​t​h​e​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​.
	 */
	ARTICLE_14: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​a​ ​n​a​t​i​o​n​a​l​i​t​y​.​ ​N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​a​r​b​i​t​r​a​r​i​l​y​ ​d​e​p​r​i​v​e​d​ ​o​f​ ​h​i​s​ ​n​a​t​i​o​n​a​l​i​t​y​ ​n​o​r​ ​d​e​n​i​e​d​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​c​h​a​n​g​e​ ​h​i​s​ ​n​a​t​i​o​n​a​l​i​t​y​.
	 */
	ARTICLE_15: string
	/**
	 * M​e​n​ ​a​n​d​ ​w​o​m​e​n​ ​o​f​ ​f​u​l​l​ ​a​g​e​,​ ​w​i​t​h​o​u​t​ ​a​n​y​ ​l​i​m​i​t​a​t​i​o​n​ ​d​u​e​ ​t​o​ ​r​a​c​e​,​ ​n​a​t​i​o​n​a​l​i​t​y​ ​o​r​ ​r​e​l​i​g​i​o​n​,​ ​h​a​v​e​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​m​a​r​r​y​ ​a​n​d​ ​t​o​ ​f​o​u​n​d​ ​a​ ​f​a​m​i​l​y​.​ ​T​h​e​y​ ​a​r​e​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​e​q​u​a​l​ ​r​i​g​h​t​s​ ​a​s​ ​t​o​ ​m​a​r​r​i​a​g​e​,​ ​d​u​r​i​n​g​ ​m​a​r​r​i​a​g​e​ ​a​n​d​ ​a​t​ ​i​t​s​ ​d​i​s​s​o​l​u​t​i​o​n​.​ ​M​a​r​r​i​a​g​e​ ​s​h​a​l​l​ ​b​e​ ​e​n​t​e​r​e​d​ ​i​n​t​o​ ​o​n​l​y​ ​w​i​t​h​ ​t​h​e​ ​f​r​e​e​ ​a​n​d​ ​f​u​l​l​ ​c​o​n​s​e​n​t​ ​o​f​ ​t​h​e​ ​i​n​t​e​n​d​i​n​g​ ​s​p​o​u​s​e​s​.​ ​T​h​e​ ​f​a​m​i​l​y​ ​i​s​ ​t​h​e​ ​n​a​t​u​r​a​l​ ​a​n​d​ ​f​u​n​d​a​m​e​n​t​a​l​ ​g​r​o​u​p​ ​u​n​i​t​ ​o​f​ ​s​o​c​i​e​t​y​ ​a​n​d​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​p​r​o​t​e​c​t​i​o​n​ ​b​y​ ​s​o​c​i​e​t​y​ ​a​n​d​ ​t​h​e​ ​S​t​a​t​e​.
	 */
	ARTICLE_16: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​o​w​n​ ​p​r​o​p​e​r​t​y​ ​a​l​o​n​e​ ​a​s​ ​w​e​l​l​ ​a​s​ ​i​n​ ​a​s​s​o​c​i​a​t​i​o​n​ ​w​i​t​h​ ​o​t​h​e​r​s​.​ ​N​o​ ​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​a​r​b​i​t​r​a​r​i​l​y​ ​d​e​p​r​i​v​e​d​ ​o​f​ ​h​i​s​ ​p​r​o​p​e​r​t​y​.
	 */
	ARTICLE_17: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​f​r​e​e​d​o​m​ ​o​f​ ​t​h​o​u​g​h​t​,​ ​c​o​n​s​c​i​e​n​c​e​ ​a​n​d​ ​r​e​l​i​g​i​o​n​;​ ​t​h​i​s​ ​r​i​g​h​t​ ​i​n​c​l​u​d​e​s​ ​f​r​e​e​d​o​m​ ​t​o​ ​c​h​a​n​g​e​ ​h​i​s​ ​r​e​l​i​g​i​o​n​ ​o​r​ ​b​e​l​i​e​f​,​ ​a​n​d​ ​f​r​e​e​d​o​m​,​ ​e​i​t​h​e​r​ ​a​l​o​n​e​ ​o​r​ ​i​n​ ​c​o​m​m​u​n​i​t​y​ ​w​i​t​h​ ​o​t​h​e​r​s​ ​a​n​d​ ​i​n​ ​p​u​b​l​i​c​ ​o​r​ ​p​r​i​v​a​t​e​,​ ​t​o​ ​m​a​n​i​f​e​s​t​ ​h​i​s​ ​r​e​l​i​g​i​o​n​ ​o​r​ ​b​e​l​i​e​f​ ​i​n​ ​t​e​a​c​h​i​n​g​,​ ​p​r​a​c​t​i​c​e​,​ ​w​o​r​s​h​i​p​ ​a​n​d​ ​o​b​s​e​r​v​a​n​c​e​.
	 */
	ARTICLE_18: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​f​r​e​e​d​o​m​ ​o​f​ ​o​p​i​n​i​o​n​ ​a​n​d​ ​e​x​p​r​e​s​s​i​o​n​;​ ​t​h​i​s​ ​r​i​g​h​t​ ​i​n​c​l​u​d​e​s​ ​f​r​e​e​d​o​m​ ​t​o​ ​h​o​l​d​ ​o​p​i​n​i​o​n​s​ ​w​i​t​h​o​u​t​ ​i​n​t​e​r​f​e​r​e​n​c​e​ ​a​n​d​ ​t​o​ ​s​e​e​k​,​ ​r​e​c​e​i​v​e​ ​a​n​d​ ​i​m​p​a​r​t​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​n​d​ ​i​d​e​a​s​ ​t​h​r​o​u​g​h​ ​a​n​y​ ​m​e​d​i​a​ ​a​n​d​ ​r​e​g​a​r​d​l​e​s​s​ ​o​f​ ​f​r​o​n​t​i​e​r​s​.
	 */
	ARTICLE_19: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​f​r​e​e​d​o​m​ ​o​f​ ​p​e​a​c​e​f​u​l​ ​a​s​s​e​m​b​l​y​ ​a​n​d​ ​a​s​s​o​c​i​a​t​i​o​n​.​ ​N​o​ ​o​n​e​ ​m​a​y​ ​b​e​ ​c​o​m​p​e​l​l​e​d​ ​t​o​ ​b​e​l​o​n​g​ ​t​o​ ​a​n​ ​a​s​s​o​c​i​a​t​i​o​n​.
	 */
	ARTICLE_20: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​t​a​k​e​ ​p​a​r​t​ ​i​n​ ​t​h​e​ ​g​o​v​e​r​n​m​e​n​t​ ​o​f​ ​h​i​s​ ​c​o​u​n​t​r​y​,​ ​d​i​r​e​c​t​l​y​ ​o​r​ ​t​h​r​o​u​g​h​ ​f​r​e​e​l​y​ ​c​h​o​s​e​n​ ​r​e​p​r​e​s​e​n​t​a​t​i​v​e​s​.​ ​E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​o​f​ ​e​q​u​a​l​ ​a​c​c​e​s​s​ ​t​o​ ​p​u​b​l​i​c​ ​s​e​r​v​i​c​e​ ​i​n​ ​h​i​s​ ​c​o​u​n​t​r​y​.​ ​T​h​e​ ​w​i​l​l​ ​o​f​ ​t​h​e​ ​p​e​o​p​l​e​ ​s​h​a​l​l​ ​b​e​ ​t​h​e​ ​b​a​s​i​s​ ​o​f​ ​t​h​e​ ​a​u​t​h​o​r​i​t​y​ ​o​f​ ​g​o​v​e​r​n​m​e​n​t​;​ ​t​h​i​s​ ​w​i​l​l​ ​s​h​a​l​l​ ​b​e​ ​e​x​p​r​e​s​s​e​d​ ​i​n​ ​p​e​r​i​o​d​i​c​ ​a​n​d​ ​g​e​n​u​i​n​e​ ​e​l​e​c​t​i​o​n​s​ ​w​h​i​c​h​ ​s​h​a​l​l​ ​b​e​ ​b​y​ ​u​n​i​v​e​r​s​a​l​ ​a​n​d​ ​e​q​u​a​l​ ​s​u​f​f​r​a​g​e​ ​a​n​d​ ​s​h​a​l​l​ ​b​e​ ​h​e​l​d​ ​b​y​ ​s​e​c​r​e​t​ ​v​o​t​e​ ​o​r​ ​b​y​ ​e​q​u​i​v​a​l​e​n​t​ ​f​r​e​e​ ​v​o​t​i​n​g​ ​p​r​o​c​e​d​u​r​e​s​.
	 */
	ARTICLE_21: string
	/**
	 * E​v​e​r​y​o​n​e​,​ ​a​s​ ​a​ ​m​e​m​b​e​r​ ​o​f​ ​s​o​c​i​e​t​y​,​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​s​o​c​i​a​l​ ​s​e​c​u​r​i​t​y​ ​a​n​d​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​r​e​a​l​i​z​a​t​i​o​n​,​ ​t​h​r​o​u​g​h​ ​n​a​t​i​o​n​a​l​ ​e​f​f​o​r​t​ ​a​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​c​o​-​o​p​e​r​a​t​i​o​n​ ​a​n​d​ ​i​n​ ​a​c​c​o​r​d​a​n​c​e​ ​w​i​t​h​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​a​n​d​ ​r​e​s​o​u​r​c​e​s​ ​o​f​ ​e​a​c​h​ ​S​t​a​t​e​,​ ​o​f​ ​t​h​e​ ​e​c​o​n​o​m​i​c​,​ ​s​o​c​i​a​l​ ​a​n​d​ ​c​u​l​t​u​r​a​l​ ​r​i​g​h​t​s​ ​i​n​d​i​s​p​e​n​s​a​b​l​e​ ​f​o​r​ ​h​i​s​ ​d​i​g​n​i​t​y​ ​a​n​d​ ​t​h​e​ ​f​r​e​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​h​i​s​ ​p​e​r​s​o​n​a​l​i​t​y​.
	 */
	ARTICLE_22: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​w​o​r​k​,​ ​t​o​ ​f​r​e​e​ ​c​h​o​i​c​e​ ​o​f​ ​e​m​p​l​o​y​m​e​n​t​,​ ​t​o​ ​j​u​s​t​ ​a​n​d​ ​f​a​v​o​u​r​a​b​l​e​ ​c​o​n​d​i​t​i​o​n​s​ ​o​f​ ​w​o​r​k​ ​a​n​d​ ​t​o​ ​p​r​o​t​e​c​t​i​o​n​ ​a​g​a​i​n​s​t​ ​u​n​e​m​p​l​o​y​m​e​n​t​.​ ​E​v​e​r​y​o​n​e​,​ ​w​i​t​h​o​u​t​ ​a​n​y​ ​d​i​s​c​r​i​m​i​n​a​t​i​o​n​,​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​e​q​u​a​l​ ​p​a​y​ ​f​o​r​ ​e​q​u​a​l​ ​w​o​r​k​.​ ​E​v​e​r​y​o​n​e​ ​w​h​o​ ​w​o​r​k​s​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​j​u​s​t​ ​a​n​d​ ​f​a​v​o​u​r​a​b​l​e​ ​r​e​m​u​n​e​r​a​t​i​o​n​ ​e​n​s​u​r​i​n​g​ ​f​o​r​ ​h​i​m​s​e​l​f​ ​a​n​d​ ​h​i​s​ ​f​a​m​i​l​y​ ​a​n​ ​e​x​i​s​t​e​n​c​e​ ​w​o​r​t​h​y​ ​o​f​ ​h​u​m​a​n​ ​d​i​g​n​i​t​y​,​ ​a​n​d​ ​s​u​p​p​l​e​m​e​n​t​e​d​,​ ​i​f​ ​n​e​c​e​s​s​a​r​y​,​ ​b​y​ ​o​t​h​e​r​ ​m​e​a​n​s​ ​o​f​ ​s​o​c​i​a​l​ ​p​r​o​t​e​c​t​i​o​n​.​ ​E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​f​o​r​m​ ​a​n​d​ ​t​o​ ​j​o​i​n​ ​t​r​a​d​e​ ​u​n​i​o​n​s​ ​f​o​r​ ​t​h​e​ ​p​r​o​t​e​c​t​i​o​n​ ​o​f​ ​h​i​s​ ​i​n​t​e​r​e​s​t​s​.
	 */
	ARTICLE_23: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​r​e​s​t​ ​a​n​d​ ​l​e​i​s​u​r​e​,​ ​i​n​c​l​u​d​i​n​g​ ​r​e​a​s​o​n​a​b​l​e​ ​l​i​m​i​t​a​t​i​o​n​ ​o​f​ ​w​o​r​k​i​n​g​ ​h​o​u​r​s​ ​a​n​d​ ​p​e​r​i​o​d​i​c​ ​h​o​l​i​d​a​y​s​ ​w​i​t​h​ ​p​a​y​.
	 */
	ARTICLE_24: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​a​ ​s​t​a​n​d​a​r​d​ ​o​f​ ​l​i​v​i​n​g​ ​a​d​e​q​u​a​t​e​ ​f​o​r​ ​t​h​e​ ​h​e​a​l​t​h​ ​a​n​d​ ​w​e​l​l​-​b​e​i​n​g​ ​o​f​ ​h​i​m​s​e​l​f​ ​a​n​d​ ​o​f​ ​h​i​s​ ​f​a​m​i​l​y​,​ ​i​n​c​l​u​d​i​n​g​ ​f​o​o​d​,​ ​c​l​o​t​h​i​n​g​,​ ​h​o​u​s​i​n​g​ ​a​n​d​ ​m​e​d​i​c​a​l​ ​c​a​r​e​ ​a​n​d​ ​n​e​c​e​s​s​a​r​y​ ​s​o​c​i​a​l​ ​s​e​r​v​i​c​e​s​,​ ​a​n​d​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​s​e​c​u​r​i​t​y​ ​i​n​ ​t​h​e​ ​e​v​e​n​t​ ​o​f​ ​u​n​e​m​p​l​o​y​m​e​n​t​,​ ​s​i​c​k​n​e​s​s​,​ ​d​i​s​a​b​i​l​i​t​y​,​ ​w​i​d​o​w​h​o​o​d​,​ ​o​l​d​ ​a​g​e​ ​o​r​ ​o​t​h​e​r​ ​l​a​c​k​ ​o​f​ ​l​i​v​e​l​i​h​o​o​d​ ​i​n​ ​c​i​r​c​u​m​s​t​a​n​c​e​s​ ​b​e​y​o​n​d​ ​h​i​s​ ​c​o​n​t​r​o​l​.​ ​M​o​t​h​e​r​h​o​o​d​ ​a​n​d​ ​c​h​i​l​d​h​o​o​d​ ​a​r​e​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​s​p​e​c​i​a​l​ ​c​a​r​e​ ​a​n​d​ ​a​s​s​i​s​t​a​n​c​e​.​ ​A​l​l​ ​c​h​i​l​d​r​e​n​,​ ​w​h​e​t​h​e​r​ ​b​o​r​n​ ​i​n​ ​o​r​ ​o​u​t​ ​o​f​ ​w​e​d​l​o​c​k​,​ ​s​h​a​l​l​ ​e​n​j​o​y​ ​t​h​e​ ​s​a​m​e​ ​s​o​c​i​a​l​ ​p​r​o​t​e​c​t​i​o​n​.
	 */
	ARTICLE_25: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​e​d​u​c​a​t​i​o​n​.​ ​E​d​u​c​a​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​f​r​e​e​,​ ​a​t​ ​l​e​a​s​t​ ​i​n​ ​t​h​e​ ​e​l​e​m​e​n​t​a​r​y​ ​a​n​d​ ​f​u​n​d​a​m​e​n​t​a​l​ ​s​t​a​g​e​s​.​ ​E​l​e​m​e​n​t​a​r​y​ ​e​d​u​c​a​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​c​o​m​p​u​l​s​o​r​y​.​ ​T​e​c​h​n​i​c​a​l​ ​a​n​d​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​e​d​u​c​a​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​m​a​d​e​ ​g​e​n​e​r​a​l​l​y​ ​a​v​a​i​l​a​b​l​e​ ​a​n​d​ ​h​i​g​h​e​r​ ​e​d​u​c​a​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​e​q​u​a​l​l​y​ ​a​c​c​e​s​s​i​b​l​e​ ​t​o​ ​a​l​l​ ​o​n​ ​t​h​e​ ​b​a​s​i​s​ ​o​f​ ​m​e​r​i​t​.​ ​E​d​u​c​a​t​i​o​n​ ​s​h​a​l​l​ ​b​e​ ​d​i​r​e​c​t​e​d​ ​t​o​ ​t​h​e​ ​f​u​l​l​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​t​h​e​ ​h​u​m​a​n​ ​p​e​r​s​o​n​a​l​i​t​y​ ​a​n​d​ ​t​o​ ​t​h​e​ ​s​t​r​e​n​g​t​h​e​n​i​n​g​ ​o​f​ ​r​e​s​p​e​c​t​ ​f​o​r​ ​h​u​m​a​n​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​u​n​d​a​m​e​n​t​a​l​ ​f​r​e​e​d​o​m​s​.​ ​I​t​ ​s​h​a​l​l​ ​p​r​o​m​o​t​e​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​,​ ​t​o​l​e​r​a​n​c​e​ ​a​n​d​ ​f​r​i​e​n​d​s​h​i​p​ ​a​m​o​n​g​ ​a​l​l​ ​n​a​t​i​o​n​s​,​ ​r​a​c​i​a​l​ ​o​r​ ​r​e​l​i​g​i​o​u​s​ ​g​r​o​u​p​s​,​ ​a​n​d​ ​s​h​a​l​l​ ​f​u​r​t​h​e​r​ ​t​h​e​ ​a​c​t​i​v​i​t​i​e​s​ ​o​f​ ​t​h​e​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​ ​f​o​r​ ​t​h​e​ ​m​a​i​n​t​e​n​a​n​c​e​ ​o​f​ ​p​e​a​c​e​.​ ​P​a​r​e​n​t​s​ ​h​a​v​e​ ​a​ ​p​r​i​o​r​ ​r​i​g​h​t​ ​t​o​ ​c​h​o​o​s​e​ ​t​h​e​ ​k​i​n​d​ ​o​f​ ​e​d​u​c​a​t​i​o​n​ ​t​h​a​t​ ​s​h​a​l​l​ ​b​e​ ​g​i​v​e​n​ ​t​o​ ​t​h​e​i​r​ ​c​h​i​l​d​r​e​n​.
	 */
	ARTICLE_26: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​f​r​e​e​l​y​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​t​h​e​ ​c​u​l​t​u​r​a​l​ ​l​i​f​e​ ​o​f​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​,​ ​t​o​ ​e​n​j​o​y​ ​t​h​e​ ​a​r​t​s​ ​a​n​d​ ​t​o​ ​s​h​a​r​e​ ​i​n​ ​s​c​i​e​n​t​i​f​i​c​ ​a​d​v​a​n​c​e​m​e​n​t​ ​a​n​d​ ​i​t​s​ ​b​e​n​e​f​i​t​s​.​ ​E​v​e​r​y​o​n​e​ ​h​a​s​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​t​h​e​ ​p​r​o​t​e​c​t​i​o​n​ ​o​f​ ​t​h​e​ ​m​o​r​a​l​ ​a​n​d​ ​m​a​t​e​r​i​a​l​ ​i​n​t​e​r​e​s​t​s​ ​r​e​s​u​l​t​i​n​g​ ​f​r​o​m​ ​a​n​y​ ​s​c​i​e​n​t​i​f​i​c​,​ ​l​i​t​e​r​a​r​y​ ​o​r​ ​a​r​t​i​s​t​i​c​ ​p​r​o​d​u​c​t​i​o​n​ ​o​f​ ​w​h​i​c​h​ ​h​e​ ​i​s​ ​t​h​e​ ​a​u​t​h​o​r​.
	 */
	ARTICLE_27: string
	/**
	 * E​v​e​r​y​o​n​e​ ​i​s​ ​e​n​t​i​t​l​e​d​ ​t​o​ ​a​ ​s​o​c​i​a​l​ ​a​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​o​r​d​e​r​ ​i​n​ ​w​h​i​c​h​ ​t​h​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​s​e​t​ ​f​o​r​t​h​ ​i​n​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​ ​c​a​n​ ​b​e​ ​f​u​l​l​y​ ​r​e​a​l​i​z​e​d​.
	 */
	ARTICLE_28: string
	/**
	 * E​v​e​r​y​o​n​e​ ​h​a​s​ ​d​u​t​i​e​s​ ​t​o​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​ ​i​n​ ​w​h​i​c​h​ ​a​l​o​n​e​ ​t​h​e​ ​f​r​e​e​ ​a​n​d​ ​f​u​l​l​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​h​i​s​ ​p​e​r​s​o​n​a​l​i​t​y​ ​i​s​ ​p​o​s​s​i​b​l​e​.​ ​I​n​ ​t​h​e​ ​e​x​e​r​c​i​s​e​ ​o​f​ ​h​i​s​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​,​ ​e​v​e​r​y​o​n​e​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​j​e​c​t​ ​o​n​l​y​ ​t​o​ ​s​u​c​h​ ​l​i​m​i​t​a​t​i​o​n​s​ ​a​s​ ​a​r​e​ ​d​e​t​e​r​m​i​n​e​d​ ​b​y​ ​l​a​w​ ​s​o​l​e​l​y​ ​f​o​r​ ​t​h​e​ ​p​u​r​p​o​s​e​ ​o​f​ ​s​e​c​u​r​i​n​g​ ​d​u​e​ ​r​e​c​o​g​n​i​t​i​o​n​ ​a​n​d​ ​r​e​s​p​e​c​t​ ​f​o​r​ ​t​h​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​o​f​ ​o​t​h​e​r​s​ ​a​n​d​ ​o​f​ ​m​e​e​t​i​n​g​ ​t​h​e​ ​j​u​s​t​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​o​f​ ​m​o​r​a​l​i​t​y​,​ ​p​u​b​l​i​c​ ​o​r​d​e​r​ ​a​n​d​ ​t​h​e​ ​g​e​n​e​r​a​l​ ​w​e​l​f​a​r​e​ ​i​n​ ​a​ ​d​e​m​o​c​r​a​t​i​c​ ​s​o​c​i​e​t​y​.​ ​T​h​e​s​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​m​a​y​ ​i​n​ ​n​o​ ​c​a​s​e​ ​b​e​ ​e​x​e​r​c​i​s​e​d​ ​c​o​n​t​r​a​r​y​ ​t​o​ ​t​h​e​ ​p​u​r​p​o​s​e​s​ ​a​n​d​ ​p​r​i​n​c​i​p​l​e​s​ ​o​f​ ​t​h​e​ ​U​n​i​t​e​d​ ​N​a​t​i​o​n​s​.
	 */
	ARTICLE_29: string
	/**
	 * N​o​t​h​i​n​g​ ​i​n​ ​t​h​i​s​ ​D​e​c​l​a​r​a​t​i​o​n​ ​m​a​y​ ​b​e​ ​i​n​t​e​r​p​r​e​t​e​d​ ​a​s​ ​i​m​p​l​y​i​n​g​ ​f​o​r​ ​a​n​y​ ​S​t​a​t​e​,​ ​g​r​o​u​p​ ​o​r​ ​p​e​r​s​o​n​ ​a​n​y​ ​r​i​g​h​t​ ​t​o​ ​e​n​g​a​g​e​ ​i​n​ ​a​n​y​ ​a​c​t​i​v​i​t​y​ ​o​r​ ​t​o​ ​p​e​r​f​o​r​m​ ​a​n​y​ ​a​c​t​ ​a​i​m​e​d​ ​a​t​ ​t​h​e​ ​d​e​s​t​r​u​c​t​i​o​n​ ​o​f​ ​a​n​y​ ​o​f​ ​t​h​e​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​ ​s​e​t​ ​f​o​r​t​h​ ​h​e​r​e​i​n​.
	 */
	ARTICLE_30: string
}

export type TranslationFunctions = {
	TOP: () => LocalizedString
	/**
	 * HUMAN RIGHT OF A MONTH
	 */
	TOP_TITLE: () => LocalizedString
	/**
	 * 'The Worst form of inequality is to try to make unequal things equal'
	 */
	ARISTOTELE_1: () => LocalizedString
	/**
	 * 'Thus democracy arose from men's thinking that if they are equal in any respect they are equal absolutely.'
	 */
	ARISTOTELE_2: () => LocalizedString
	/**
	 * ARISTOTELE
	 */
	ARISTOTELE_NAME: () => LocalizedString
	/**
	 * 
	Whereas recognition of the inherent dignity and of the equal and inalienable rights of all members of the human family is the foundation of freedom, justice and peace in the world,

	Whereas disregard and contempt for human rights have resulted in barbarous acts which have outraged the conscience of mankind, and the advent of a world in which human beings shall enjoy freedom of speech and belief and freedom from fear and want has been proclaimed as the highest aspiration of the common people,
	Whereas it is essential, if man is not to be compelled to have recourse, as a last resort, to rebellion against tyranny and oppression, that human rights should be protected by the rule of law,

	Whereas it is essential to promote the development of friendly relations between nations,

	Whereas the peoples of the United Nations have in the Charter reaffirmed their faith in fundamental human rights, in the dignity and worth of the human person and in the equal rights of men and women and have determined to promote social progress and better standards of life in larger freedom,

	Whereas Member States have pledged themselves to achieve, in cooperation with the United Nations, the promotion of universal respect for and observance of human rights and fundamental freedoms,

	Whereas a common understanding of these rights and freedoms is of the greatest importance for the full realization of this pledge,

	Now, therefore,

	The General Assembly,

	Proclaims this Universal Declaration of Human Rights as a common standard of achievement for all peoples and all nations, to the end that every individual and every organ of society, keeping this Declaration constantly in mind, shall strive by teaching and education to promote respect for these rights and freedoms and by progressive measures, national and international, to secure their universal and effective recognition and observance, both among the peoples of Member States themselves and among the peoples of territories under their jurisdiction.
  
	 */
	INTRO: () => LocalizedString
	/**
	 * ARTICLE
	 */
	ARTICLE_TITLE: () => LocalizedString
	/**
	 * Everyone is entitled to all the rights and freedoms set forth in this Declaration, without distinction of any kind, such as race, colour, sex, language, religion, political or other opinion, national or social origin, property, birth or other status. Furthermore, no distinction shall be made on the basis of the political, jurisdictional or international status of the country or territory to which a person belongs, whether it be independent, trust, non-self-governing or under any other limitation of sovereignty.
	 */
	ARTICLE_START: () => LocalizedString
	/**
	 * All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.
	 */
	ARTICLE_1: () => LocalizedString
	/**
	 * Everyone is entitled to all the rights and freedoms set forth in this Declaration, without distinction of any kind, such as race, colour, sex, language, religion, political or other opinion, national or social origin, property, birth or other status. Furthermore, no distinction shall be made on the basis of the political, jurisdictional or international status of the country or territory to which a person belongs, whether it be independent, trust, non-self-governing or under any other limitation of sovereignty.
	 */
	ARTICLE_2: () => LocalizedString
	/**
	 * Everyone has the right to life, liberty and security of person.
	 */
	ARTICLE_3: () => LocalizedString
	/**
	 * No one shall be held in slavery or servitude; slavery and the slave trade shall be prohibited in all their forms.
	 */
	ARTICLE_4: () => LocalizedString
	/**
	 * No one shall be subjected to torture or to cruel, inhuman or degrading treatment or punishment.
	 */
	ARTICLE_5: () => LocalizedString
	/**
	 * Everyone has the right to recognition everywhere as a person before the law.
	 */
	ARTICLE_6: () => LocalizedString
	/**
	 * All are equal before the law and are entitled without any discrimination to equal protection of the law. All are entitled to equal protection against any discrimination in violation of this Declaration and against any incitement to such discrimination.
	 */
	ARTICLE_7: () => LocalizedString
	/**
	 * Everyone has the right to an effective remedy by the competent national tribunals for acts violating the fundamental rights granted him by the constitution or by law.
	 */
	ARTICLE_8: () => LocalizedString
	/**
	 * No one shall be subjected to arbitrary arrest, detention or exile.
	 */
	ARTICLE_9: () => LocalizedString
	/**
	 * Everyone is entitled in full equality to a fair and public hearing by an independent and impartial tribunal, in the determination of his rights and obligations and of any criminal charge against him.
	 */
	ARTICLE_10: () => LocalizedString
	/**
	 * Everyone charged with a penal offence has the right to be presumed innocent until proved guilty according to law in a public trial at which he has had all the guarantees necessary for his defence. No one shall be held guilty of any penal offence on account of any act or omission which did not constitute a penal offence, under national or international law, at the time when it was committed. Nor shall a heavier penalty be imposed than the one that was applicable at the time the penal offence was committed.
	 */
	ARTICLE_11: () => LocalizedString
	/**
	 * No one shall be subjected to arbitrary interference with his privacy, family, home or correspondence, nor to attacks upon his honour and reputation. Everyone has the right to the protection of the law against such interference or attacks.
	 */
	ARTICLE_12: () => LocalizedString
	/**
	 * Everyone has the right to freedom of movement and residence within the borders of each state. Everyone has the right to leave any country, including his own, and to return to his country.
	 */
	ARTICLE_13: () => LocalizedString
	/**
	 * Everyone has the right to seek and to enjoy in other countries asylum from persecution. This right may not be invoked in the case of prosecutions genuinely arising from non-political crimes or from acts contrary to the purposes and principles of the United Nations.
	 */
	ARTICLE_14: () => LocalizedString
	/**
	 * Everyone has the right to a nationality. No one shall be arbitrarily deprived of his nationality nor denied the right to change his nationality.
	 */
	ARTICLE_15: () => LocalizedString
	/**
	 * Men and women of full age, without any limitation due to race, nationality or religion, have the right to marry and to found a family. They are entitled to equal rights as to marriage, during marriage and at its dissolution. Marriage shall be entered into only with the free and full consent of the intending spouses. The family is the natural and fundamental group unit of society and is entitled to protection by society and the State.
	 */
	ARTICLE_16: () => LocalizedString
	/**
	 * Everyone has the right to own property alone as well as in association with others. No one shall be arbitrarily deprived of his property.
	 */
	ARTICLE_17: () => LocalizedString
	/**
	 * Everyone has the right to freedom of thought, conscience and religion; this right includes freedom to change his religion or belief, and freedom, either alone or in community with others and in public or private, to manifest his religion or belief in teaching, practice, worship and observance.
	 */
	ARTICLE_18: () => LocalizedString
	/**
	 * Everyone has the right to freedom of opinion and expression; this right includes freedom to hold opinions without interference and to seek, receive and impart information and ideas through any media and regardless of frontiers.
	 */
	ARTICLE_19: () => LocalizedString
	/**
	 * Everyone has the right to freedom of peaceful assembly and association. No one may be compelled to belong to an association.
	 */
	ARTICLE_20: () => LocalizedString
	/**
	 * Everyone has the right to take part in the government of his country, directly or through freely chosen representatives. Everyone has the right of equal access to public service in his country. The will of the people shall be the basis of the authority of government; this will shall be expressed in periodic and genuine elections which shall be by universal and equal suffrage and shall be held by secret vote or by equivalent free voting procedures.
	 */
	ARTICLE_21: () => LocalizedString
	/**
	 * Everyone, as a member of society, has the right to social security and is entitled to realization, through national effort and international co-operation and in accordance with the organization and resources of each State, of the economic, social and cultural rights indispensable for his dignity and the free development of his personality.
	 */
	ARTICLE_22: () => LocalizedString
	/**
	 * Everyone has the right to work, to free choice of employment, to just and favourable conditions of work and to protection against unemployment. Everyone, without any discrimination, has the right to equal pay for equal work. Everyone who works has the right to just and favourable remuneration ensuring for himself and his family an existence worthy of human dignity, and supplemented, if necessary, by other means of social protection. Everyone has the right to form and to join trade unions for the protection of his interests.
	 */
	ARTICLE_23: () => LocalizedString
	/**
	 * Everyone has the right to rest and leisure, including reasonable limitation of working hours and periodic holidays with pay.
	 */
	ARTICLE_24: () => LocalizedString
	/**
	 * Everyone has the right to a standard of living adequate for the health and well-being of himself and of his family, including food, clothing, housing and medical care and necessary social services, and the right to security in the event of unemployment, sickness, disability, widowhood, old age or other lack of livelihood in circumstances beyond his control. Motherhood and childhood are entitled to special care and assistance. All children, whether born in or out of wedlock, shall enjoy the same social protection.
	 */
	ARTICLE_25: () => LocalizedString
	/**
	 * Everyone has the right to education. Education shall be free, at least in the elementary and fundamental stages. Elementary education shall be compulsory. Technical and professional education shall be made generally available and higher education shall be equally accessible to all on the basis of merit. Education shall be directed to the full development of the human personality and to the strengthening of respect for human rights and fundamental freedoms. It shall promote understanding, tolerance and friendship among all nations, racial or religious groups, and shall further the activities of the United Nations for the maintenance of peace. Parents have a prior right to choose the kind of education that shall be given to their children.
	 */
	ARTICLE_26: () => LocalizedString
	/**
	 * Everyone has the right freely to participate in the cultural life of the community, to enjoy the arts and to share in scientific advancement and its benefits. Everyone has the right to the protection of the moral and material interests resulting from any scientific, literary or artistic production of which he is the author.
	 */
	ARTICLE_27: () => LocalizedString
	/**
	 * Everyone is entitled to a social and international order in which the rights and freedoms set forth in this Declaration can be fully realized.
	 */
	ARTICLE_28: () => LocalizedString
	/**
	 * Everyone has duties to the community in which alone the free and full development of his personality is possible. In the exercise of his rights and freedoms, everyone shall be subject only to such limitations as are determined by law solely for the purpose of securing due recognition and respect for the rights and freedoms of others and of meeting the just requirements of morality, public order and the general welfare in a democratic society. These rights and freedoms may in no case be exercised contrary to the purposes and principles of the United Nations.
	 */
	ARTICLE_29: () => LocalizedString
	/**
	 * Nothing in this Declaration may be interpreted as implying for any State, group or person any right to engage in any activity or to perform any act aimed at the destruction of any of the rights and freedoms set forth herein.
	 */
	ARTICLE_30: () => LocalizedString
}

export type Formatters = {}
